### ISSUE TITLE
Input variable orientation

### ISSUE THREAD

**Issue by joh-taylor** [julianeweller/MinsePIE#1]
Hi,

I was trying to test your tool but am unsure about the input (PBS and RTT).
In which `direction` should one input these sequences? The same as in a cloned pegRNA? (where e.g. the PBS is reverse complement from protospacer)
And should the insertion sequence be part of the RTT-input or should I add the RTT sequence without the insertion?

Thanks, and best regards
John

**Comment by JulianeWeller** [comment]
Hi John, 
Thanks for pointing out that the orientation should be included in the description on the main page. I just updated it accordingly. In short, all sequences should be supplied in 5' to 3' direction if the target site is on the forward strand, otherwise the reverse complement should be supplied. 
Best,
Juliane

**Comment by joh-taylor** [comment]
Just to confirm, you mean the 5' to 3' orientation on the DNA, right? So PBS region comes upstream (5') of RTT region then. (Since on the pegRNA itself you would have RTT upstream/5' of PBS).
Best, 
John

**Comment by JulianeWeller** [comment]
Hi John,
Yes, the orientation is on the DNA. I added a usage example to the markdown with a more exhaustive explanation - hope this helps! I would also recommend getting the newest version of the code, as improvements have been made to the model.
Best, Juliane
